### ISSUE TITLE
some errors in datasets

### ISSUE THREAD

**Issue by miaoct** [ltnghia/openforensics#2]
![image](https://user-images.githubusercontent.com/55660615/193575846-88173f0d-f264-4a3a-b0da-852f40331519.png)

what do '2', '3', and '4' indicate in figure? 

Where are the segmentation labels?

**Comment by ltnghia** [comment]
Thank you for your interest in OpenForensics dataset.
The dataset annotation is based on MS-COCO format.
Please install [pycocotools](https://github.com/ltnghia/openforensics#install) to read the ground-truth files.

**Comment by miaoct** [comment]
Thank you.
